config/routes.rb
Rails.application.routes.draw do 
  resources :users, only: [:new, :create]
  resources :groups, only: [:index, :new, :create, :show]
  resources :investments, only: [:index, :new, :create]
  root 'invest#index'
  get '/', to: 'sessions#home'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#logout'
  get 'profile', to: 'invest#profile'
  get 'profile', to: 'invest#profile'
  get 'investments/external', to: 'investments#external'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  validates :icon, format: { with: /.+\.(jpe?g|png)\z/,
                             message: 'only JPEG,JPG and PNG are valid formats.' },
                   allow_blank: true

  belongs_to :user
  has_and_belongs_to_many :investments

  scope :sort_by_name, -> { order(name: :asc) }

  def goal_amount_2
    goal = 0
    investments.includes(:groups).select do |investment|
      goal = investment.total_amount + goal if investment.groups.any?
    end

    goal
  end

  def goal_amount
    invested = 0
    investments.each do |investment|
      invested = investment.amount + invested
    end

    invested
  end
end

app/models/investment.rb
class Investment < ApplicationRecord
  validates :name, presence: true

  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :groups

  scope :sort_by_recent, -> { order(created_at: :desc) }

  def total_amount
    amount * groups.size
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :groups
  has_many :investments, foreign_key: :author_id, dependent: :destroy

  def my_investments
    investments.sort_by_recent.includes(:groups).select { |a| a.groups.any? }
  end

  def my_external_investments
    investments.sort_by_recent.includes(:groups).reject { |a| a.groups.any? }
  end

  def investments_total_amount
    amount = 0

    investments.includes(:groups).select do |i|
      next unless i.groups.any?

      i.groups.each_with_index do |_group, _index|
        amount = i.amount + amount
      end
    end
    amount
  end

  def external_investments_total_amount
    amount = 0

    investments.includes(:groups).select do |i|
      amount = i.amount + amount if i.groups.none?
    end
    amount
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to '/transactions' unless logged_in?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :logged_in?
  def index
    @groups = Group.all.includes([:investments])
  end

  def new
    @group = current_user.groups.new
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      redirect_to '/groups'
    else
      redirect_to '/groups/new', notice: @group.errors.full_messages
    end
  end

  def show
    @group = Group.includes([:investments]).find(params[:id])
    @investments = @group.investments.includes([:groups])
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon, :goal)
  end
end

app/controllers/invest_controller.rb
class InvestController < ApplicationController
  before_action :logged_in?, except: %i[index]
  def index
    redirect_to '/profile' if logged_in?
  end

  def profile; end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  before_action :logged_in?
  def index
    @investments = current_user.my_investments
  end

  def new
    @investment = current_user.investments.new
    @groups = Group.all
  end

  def create
    @investment = current_user.investments.new(investment_params)
    has_group = false
    params[:investment][:groups].each do |group_id|
      next unless group_id != ''

      group = Group.find(group_id)
      @investment.groups << group
      has_group = true
    end

    if @investment.save
      if has_group
        redirect_to '/investments'
      else
        redirect_to '/investments/external'
      end
    else
      redirect_to '/investments/new', notice: @investment.errors.full_messages
    end
  end

  def external
    @investments = current_user.my_external_investments
  end

  private

  def investment_params
    params.require(:investment).permit(:name, :amount)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def login; end

  def logout
    session[:user_id] = nil
    redirect_to '/'
  end

  def create
    @user = User.find_by(name: params[:name])
    if @user
      session[:user_id] = @user.id
      redirect_to '/profile'
    else
      redirect_to '/login', notice: 'User not found'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:name))
    session[:user_id] = @user.id
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/invest_helper.rb
module InvestHelper
end

app/helpers/investments_helper.rb
module InvestmentsHelper
  def show_groups(investment)
    groups_text = ''
    investment.groups.each_with_index do |group, index|
      groups_text += if index + 1 < investment.groups.size
                       "#{group.name} |"
                     else
                       group.name
                     end
    end

    groups_text
  end
end

app/views/groups/index.html.erb
  <nav class="navbar navbar-primary py-3">
  <div class="icon">
    <%=link_to root_url do %>
      <i class="fa fa-arrow-left"></i>
    <%end%>
  </div>
  <div class="title">All groups</div>
  <div></div>
</nav>
<hr>
<div class="container-fluid">
  <div class="list-group">
    <% @groups.sort_by_name.each do |group| %>
      <a href="<%= group_path(group.id)  %>" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between align-items-center">
          <% if group.icon == "" then group.icon = "http://via.placeholder.com/100?text=group+img" end%>
            <img class="rounded-circle" src="<%= group.icon %>" width="100" height="100">
            <h5 class="mb-1"><%= group.name %></h5>
            <div>
              <h6>Invested</h6>
              <p><%= if group.goal then "$ #{group.goal_amount} of $ #{group.goal}" else "$ #{group.goal_amount}" end %></p>
              </div>
              <small class="text-muted"><%= group.created_at %></small>
            </div>
          </a>
        <% end %>
      </div>
    </div>
    <div class="add-btn">
      <%= link_to "New Group", new_group_path, class: "btn btn-success" %>
    </div>

app/views/groups/new.html.erb
<%= form_for @group do |f|%>
  <nav class="navbar navbar-primary py-3">
    <div class="icon">
      <%=link_to root_url do %>
        <i class="fa fa-arrow-left"></i>
      <%end%>
    </div>
    <div class="title">Create group</div>
    <div class="submit">
      <%= f.button :submit do %>
        <i class="fa fa-arrow-right"></i>
      <% end %>
    </div>
  </nav>
  <div class="container-fluid">
    <div class="form-group">
      <%= f.label :name%>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label 'Icon (Optional)' %>
      <%= f.url_field :icon, class: "form-control" %>
      <small id="emailHelp" class="form-text text-muted">Insert URL of valid image (PNG/JPG/JPEG)</small>
    </div>
    <div class="form-group">
      <%= f.label 'Set a goal (Optional)' %>
      <%= f.number_field :goal, class: "form-control" %>
    </div>
    <%=render "shared/errors" ,object:@group%>
  </div>
<%end%>

app/views/groups/partials/_investments_list.html.erb
<div class="container-fluid">
  <div class="list-group">
    <% @investments.each do |investment| %>
      <div href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between align-items-center">
          <% if investment.groups[0].icon == "" then investment.groups[0].icon = "http://via.placeholder.com/100?text=invest+img" end%>
            <img class="rounded-circle" src="<%=  investment.groups[0].icon %>" width="100" height="100">
            <div>
              <h5 class="mb-1"><%= investment.name %></h5>
            </div>
            <div>
              <h6 class="mb-1">Amount</h6>
              <p><%= "$ #{investment.amount}"%></p>
            </div>
            <small class="text-muted"><%= investment.created_at %></small>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/groups/show.html.erb
  <nav class="navbar navbar-primary py-3">
  <div class="icon">
    <%=link_to groups_url do %>
      <i class="fa fa-arrow-left"></i>
    <%end%>
  </div>
  <div class="title"><%= @group.name %></div>
  <div></div>
</nav>
<hr>
<p class="container-fluid text-right ">Total Amount: <%= "$ #{@group.goal_amount}"%></p>
<hr>
<%=render "groups/partials/investments_list" ,object:@investments%>

app/views/invest/index.html.erb
<div class="splash">
  <div class="text-color-3 text-center logo-title">Invest</div>
  <div class="buttons-container mb-4">
    <div class="mx-4">
      <%=link_to "Log In","/login",class:"btn btn-primary"%>
      <%=link_to "Sign Up","/users/new",class:"btn btn-light"%>
    </div>
  </div>
</div>

app/views/invest/profile.html.erb
<div class="profile h-100">
  <div class="container">
    <ul class="navbar-nav mr-auto">
      <div class="d-inline-flex flex-column mb-4 user">
        <div><img class="rounded-circle mb-2" src="https://via.placeholder.com/100?text=user+img"></div>
        <%= current_user.name %>
      </div>
      <hr>
      <li class="nav-item">
        <i class="fa fa-money" aria-hidden="true"></i><%= link_to "All my investments", '/investments', class: "navbar-brand" %>
      </li>
      <li class="nav-item">
        <i class="fa fa-vcard-o" aria-hidden="true"></i><%= link_to "All my external investments", '/investments/external', class: "navbar-brand" %>
      </li>
      <li class="nav-item">
        <i class="fa fa-object-group" aria-hidden="true"></i><%= link_to "All groups", '/groups', class: "navbar-brand" %>
      </li>
      <hr>
      <li class="nav-item">
        <i class="fa fa-sign-out" aria-hidden="true"></i><%= link_to "Logout", '/logout', class: "navbar-brand" %>
      </li>
    </ul>
  </div>
</div>

app/views/investments/external.html.erb
  <nav class="navbar navbar-primary py-3">
  <div class="icon">
    <%=link_to root_url do %>
      <i class="fa fa-arrow-left"></i>
    <%end%>
  </div>
  <div class="title">All external investments</div>
  <div></div>
</nav>
<hr>
<p class="container-fluid text-right ">Total Amount: <%= "$ #{current_user.external_investments_total_amount}"%></p>
<hr>
<%=render "investments/partials/external_list" ,object:@investments%>
<div class="add-btn">
  <%= link_to "New Investment", new_investment_path, class: "btn btn-success" %>
</div>

app/views/investments/index.html.erb
  <nav class="navbar navbar-primary py-3">
  <div class="icon">
    <%=link_to root_url do %>
      <i class="fa fa-arrow-left"></i>
    <%end%>
  </div>
  <div class="title">All investments</div>
  <div></div>
</nav>
<hr>
<p class="container-fluid text-right ">Total Amount: <%= "$ #{current_user.investments_total_amount}"%></p>
<hr>
<%=render "investments/partials/list" ,object:@investments%>
<div class="add-btn">
  <%= link_to "New Investment", new_investment_path, class: "btn btn-success" %>
</div>

app/views/investments/new.html.erb
<%= form_with model: @investment do |f| %>
  <nav class="navbar navbar-primary py-3">
    <div class="icon">
      <%=link_to investments_path do %>
        <i class="fa fa-arrow-left"></i>
      <%end%>
    </div>
    <div class="title">Create investment</div>
    <div class="submit">
      <%= f.button :submit do %>
        <i class="fa fa-arrow-right"></i>
      <% end %>
    </div>
  </nav>
  <div class="container-fluid">
    <div class="form-group">
      <%= f.label :name%>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :amount %>
      <%= f.number_field :amount, class: "form-control" %>
    </div>
    <label>Group select (Optional)</label>
    <%= f.collection_check_boxes(:groups, @groups, :id, :name) do |item| %>
      <div class="form-check">
        <%= item.label %>
        <%= item.check_box %>
      </div>
    <% end %>
    <%# <%= f.collection_select :groups, @groups, :id, :name, {include_blank: "-- None --"},  {multiple: true, class: "form-control"} %>
    <%=render "shared/errors" ,object:@investment%>
  </div>
<%end%>

app/views/investments/partials/_external_list.html.erb
<div class="container-fluid">
  <div class="list-group">
    <% @investments.each do |investment| %>
      <div href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between align-items-center">
          <% icon = "http://via.placeholder.com/100" %>
          <img class="rounded-circle" src="<%=  icon %>" width="100" height="100">
          <div>
            <h5 class="mb-1"><%= investment.name %></h5>
            <p><%= show_groups(investment) %></p>
          </div>
          <div>
            <h6 class="mb-1">Amount</h6>
            <p><%= "$ #{investment.amount}"%></p>
          </div>
          <small class="text-muted"><%= investment.created_at %></small>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/investments/partials/_list.html.erb
<div class="container-fluid">
  <div class="list-group">
    <% @investments.each do |investment| %>
      <div href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between align-items-center">
          <% if investment.groups[0].icon == "" then investment.groups[0].icon = "http://via.placeholder.com/100?text=invest+img" end%>
            <img class="rounded-circle" src="<%=  investment.groups[0].icon %>" width="100" height="100">
            <div>
              <h5 class="mb-1"><%= investment.name %></h5>
              <p><%= show_groups(investment) %></p>
            </div>
            <div>
              <h6 class="mb-1">Amount</h6>
              <p><%= "$ #{investment.total_amount}"%></p>
            </div>
            <small class="text-muted"><%= investment.created_at %></small>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_errors.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f|%>
  <nav class="navbar navbar-primary py-3">
    <div class="icon">
      <%=link_to root_url do %>
        <i class="fa fa-arrow-left"></i>
      <%end%>
    </div>
    <div class="title">Register</div>
    <div class="submit">
      <%= f.button :submit, name: "register" do %>
        <i class="fa fa-arrow-right"></i>
      <% end %>
    </div>
  </nav>
  <div class="container-fluid">
    <div class="form-group">
      <%= f.label :name%>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <%=render "shared/errors" ,object:@user%>
  </div>
<%end%>